apiVersion: v1
kind: Secret
metadata:
  name: config-service-secrets
  namespace: config-server
type: Opaque
stringData:
  SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/Tomas-Mart/stackoverkata-config-repo.git"
  SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS: "services"
  SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START: "true"
  SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: "main"
  ENCRYPT_KEY: "KX9pPmTqYtXuWrZv3w6z5C8F1J4H7N2B5E9R0DcGbQa"