upstream auth_service {
  server auth1:8080;
  server auth2:8080;
  server auth3:8080;
}

server {
  listen 80;

  location /api/auth {
    proxy_pass http://auth_service;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }
}