pipeline {
    agent any

    environment {
        DATABASE_URL = 'r2dbc:postgresql://postgres-resource:5432/stackover_resource_service'
        RABBITMQ_HOST = 'rabbitmq'
        ACTIVE_PROFILE = 'ci'
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Integration Test') {
            steps {
                script {
                    docker-compose up -d postgres-resource rabbitmq
                    sh 'mvn verify -Pintegration-test'
                }
                post {
                    always {
                        docker-compose down
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                sh 'docker-compose up --build -d'
            }
        }
    }
}