apiVersion: v1
kind: ConfigMap
metadata:
  name: stackover-auth-service-config
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://stackoverkata-eureka-server:8761/eureka/"
  SPRING_R2DBC_URL: "r2dbc:postgresql://postgres-auth:5432/stackover_auth_service"
  SPRING_R2DBC_USERNAME: "postgres"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"