spring:
  application:
    name: stackover-email-service
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

eureka:
  client:
    service-url:
      defaultZone: http://stackoverkata-eureka-server:8761/eureka/