spring:
  application:
    name: stackover-profile-service
  r2dbc:
    url: r2dbc:postgresql://postgres-profile:5432/stackover_profile_service
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 5
      max-size: 15

eureka:
  client:
    service-url:
      defaultZone: http://stackoverkata-eureka-server:8761/eureka/