spring:
  application:
    name: stackover-web-client
  thymeleaf:
    cache: false

frontend:
  api:
    base-url: ${API_GATEWAY_URL:http://gateway-service:8080/api}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always