server:
  port: 8180

spring:
  application:
    name: stackover-auth-service
  config:
    import: "optional:file:./config/"
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/stackover_auth_service
    username: postgres
    password: root
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
  data:
    r2dbc:
      repositories:
        enabled: true
  liquibase:
    enabled: false
    change-log: db/changelog/db.changelog-master.xml
  flyway:
    enabled: true
    locations: classpath:db/migration

# Общие настройки для всех профилей
management:
  endpoints:
    web:
      exposure:
        include: info,health,beans
  info:
    env:
      enabled: true

feign:
  circuitbreaker:
    enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  circuitbreaker:
    instances:
      profileService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

app:
  jwt:
    access-expiration-ms: 86400000
    refresh-expiration-ms: 2592000000
    secret: KX9pPmTqYtXuWrZv3w6z5C8F1J4H7N2B5E9R0DcGbQa

logging:
  level:
    root: INFO
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql: TRACE
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG